# Example override file for a development namespace.

replicaCount: 1

image:
  repository: quay.io/openshift/origin-hello-openshift
  tag: "latest"
  pullPolicy: IfNotPresent

route:
  enabled: true
  host: ""
  tls:
    enabled: false
